language: rust
rust:
- stable
- beta
- nightly
script:
- sudo env "PATH=$PATH" cargo build --verbose --all
- export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
- sudo env "PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH" kstool x64nasm "mov rax, 3"
- sudo env "PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH" cargo test --verbose --all
matrix:
  allow_failures:
    - rust: stable
notifications:
  slack: nanowaris:AYwA3oA75Srq3fb51XNe0PYB