language: rust
rust:
  - nightly
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake; fi
  - git clone https://github.com/keystone-engine/keystone.git
  - cd keystone && mkdir build && cd build && ../make-share.sh
  - sudo make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi
  - cargo build --verbose --all
  - cargo test --verbose --all
notifications:
  slack: nanowaris:AYwA3oA75Srq3fb51XNe0PYB