language: rust
rust:
- stable
- beta
- nightly
script:
- sudo apt-get install cmake
- git clone https://github.com/keystone-engine/keystone.git
- cd keystone && mkdir build && cd build && ../make-share.sh
- sudo make install
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/
- sudo ldconfig
- cargo build --verbose --all
- cargo test --verbose --all
matrix:
  allow_failures:
    - rust: stable
notifications:
  slack: nanowaris:AYwA3oA75Srq3fb51XNe0PYB