[package]
name = "sam"
version = "0.1.2"
authors = ["Luca Marcelli <ionix@protonmail.com>"]
description = "A compile time instruction assembler."
repository = "https://github.com/ioncodes/sam"
license = "MIT"

[dependencies]
keystone = "*"