[package]
name = "sam"
version = "0.3.0"
authors = ["Luca Marcelli <ionix@protonmail.com>"]
description = "A compile time instruction assembler."
repository = "https://github.com/ioncodes/sam"
license = "MIT"
build = "build.rs"